---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
apiVersion: v1
data:
  my.cnf: |
    # For advice on how to change settings please see
    # http://dev.mysql.com/doc/refman/8.0/en/server-configuration-defaults.html
    [mysqld]
    default-authentication-plugin=mysql_native_password
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    port=3306
    # Permit both IPv4 and IPv6 connections on all server interfaces
    bind-address=*

    pid-file=/var/run/mysqld/mysqld.pid
    # To avoid xx threads didn't exit error in sysbench
    max_prepared_stmt_count=1048570

    [client]
    socket=/var/run/mysqld/mysqld.sock

    !includedir /etc/mysql/conf.d/